services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.production
    ports:
      - "${PORT:-5173}:80"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 15s
      timeout: 5s
      retries: 5

