services:
  web:
    image: ${IMAGE}
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    ports:
      - "${PORT:-5173}:5173"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5173/"]
      interval: 15s
      timeout: 5s
      retries: 5
